config/routes.rb
Rails.application.routes.draw do

  # index page route
  root 'welcome#index'

  # 'static' pages
  get 'reishi-information' => 'welcome#info', as: 'info'
  get 'about'              => 'welcome#about'

  # orders
  namespace :orders do
    root action: 'index'
    get  'new'
    post 'create'
  end
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :order, inverse_of: :comment

  default_scope ->{ order(created_at: :desc) }
  scope :recent, -> { limit(3) }

  validates :body, length: { in: 3..255 }
end

app/models/order.rb
###############################################################################
# Datatype to represent a customer's info and quantity of teas ordered.
#
# The shipping of Orders is handled via the ship() function. Orders need about
#  ten seconds to process, and then are able to be shipped.
# @see ./bin/rake buynship:ship
#
# The send_pusher callback sends the order placement event to Pusher.
#  @see https://pusher.com/
#  @todo Refactor the process in Order.send_pusher() into a concern / module.
###############################################################################
class Order < ActiveRecord::Base

  # String literals to describe Pusher events.
  PUSHER_EVENT_ORDER_RECIEVED = 'order_recieved'
  PUSHER_EVENT_ORDER_SHIPPED  = 'order_shipped'

  has_one :comment, dependent: :destroy, inverse_of: :order

  default_scope ->{ order(created_at: :desc) }
  scope :today, ->{ where('created_at >= ?', 1.day.ago) }
  scope :recent, ->{ today.limit(5) }
  scope :shipped, ->{ where('shipped = ?', true) }
  scope :ready_for_shipping, ->{ where('shipped = ?', false).where('created_at <= ?', 10.seconds.ago) }

  after_create :send_pusher

  accepts_nested_attributes_for :comment, :allow_destroy => true, :reject_if => proc { |c| c[:body].blank? } 

  validates_associated :comment
  validates :name, :street, :city, :state, :country, :postal, :quantity, presence: true
  validates :name, :city, :state, :country, length: { in: 2..50 }
  validates :street,   length: { in: 3..100 }
  validates :quantity, numericality: { only_integer: true, greater_than: 0, less_than: 101 }
  validates_format_of :postal, :with => /\A\d{5}(-\d{4})?\z/, :message => 'Invalid Postal Code'

  # 'Ships' the Order to the customer by flicking the on-button. A callback is
  #   made to the application Pusher account to send the shipment event to the
  #   appropriate channel. 
  # Imaginary business rule states it takes about ten seconds to process and ship
  #  each order.
  # @see lib/tasks/buynship.rake (./bin/rake buynship:ship)
  # @return Boolean
  #   TRUE if succesfully shipped,
  #   FALSE if Order already shipped or is not ten seconds old.
  def ship
    if (!self.shipped) && (self.created_at <= 10.seconds.ago)
      self.shipped = 1
      self.save
      send_pusher_shipment
      return true
    end

    false
  end

  private

  # Sends an event to Pusher account that a new Order has been made.
  # This could be refactored into a separate concern (which would include
  #  the CONST for event name).
  # Better control over this event hook can be applied by configuring this
  #  application to ignore callbacks unless such configuration is switched
  #  on (i.e., default off, turn on for specific tests, or for dev/prod
  #  environments). See http://railsguides.net/skip-callbacks-in-tests/.
  def send_pusher
    require 'pusher'

    Pusher.url = Rails.configuration.x.pusher.url

    Pusher[Rails.configuration.x.pusher.channel].trigger(
      PUSHER_EVENT_ORDER_RECIEVED,
      { order: self.to_json(:only => [ :name, :city, :country, :quantity ]) }
    )

    true
  end

  # Sends an event to Pusher account that an Order has been shipped. 
  # @see Order::send_pusher (refactor into seperate concern)
  def send_pusher_shipment
    require 'pusher'

    Pusher.url = Rails.configuration.x.pusher.url

    Pusher[Rails.configuration.x.pusher.channel].trigger(
      PUSHER_EVENT_ORDER_SHIPPED,
      { order: self.to_json(:only => :quantity ) }
    )

    true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include RecentComments
end

app/controllers/concerns/recent_comments.rb
#############################################
# Allows selecting of sidebar Comment data
#############################################
module RecentComments
  def sidebar_recent_comments
    @sidebar_comments = Comment.recent.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :sidebar_recent_comments

  # Loads the page of Orders and related information.
  def index
    @recent_orders         = Order.recent.all
    @today_order_count     = Order.today.sum('quantity')
    @today_shipped_count   = Order.today.shipped.sum('quantity')
    @alltime_order_count   = Order.sum('quantity')
    @alltime_shipped_count = Order.shipped.sum('quantity')
  end

  # Action to allow user to place a new Order. Allows query params for
  #  `name` and /or `quantity`.
  def new
    @order = Order.new
    @order.build_comment

    if params[:name] && !params[:name].empty?
      @order.name = params[:name]
    end

    if params[:quantity] && !params[:quantity].empty?
      @order.quantity = params[:quantity]
    end
  end

  # Action to create a new Order.
  def create
    @order = Order.new(order_params)

    if @order.save
      flash[:notice] = 'Order succesfully submitted!'
      redirect_to orders_root_path
    else
      render 'new'
    end
  end

  private

  def order_params
    params.require(:order).permit(:name, :street, :city, :state, :postal, :country, :quantity, comment_attributes: [:body])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :sidebar_recent_comments

  def index
  end

  def info
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The World's Best Reishi Tea</title>
  <meta name="description" content="A Demo Rails 4 Application">
  <meta name="author" content="Todd Morningstar">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'partials/header' %>
  <div id="content-container" class="container">
    <%= yield %>
  </div>
  <div class="voffset20"></div>
   <%= render 'partials/footer' %>
</body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<!-- main content -->
<div id="orders-index-content" class="col-md-8">

  <% if flash[:notice] %>
    <div class="row">
      <div class="notice order-flash-notice alert alert-success">
        <%= flash[:notice] %> <span class="badge pull-right">X</span>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="lead">
      <h1>Reishi Tea Orders</h1>
      <small><%= link_to 'Click here', :orders_new %> to jump on this bountiful beverage bandwagon.</small>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 recent-orders-container">
      <div class="lead">
        <big>Recent Orders</big>
      </div>
      <div class='recent-orders'>
      <% if @recent_orders %>
        <% @recent_orders.each do |recent_order| %>
          <div class="recent-order list-group">
            <p class="list-group-item list-group-item-success">
              Name: <%= recent_order.name %>
            </p>
            <p class="list-group-item">
              City: <%= recent_order.city %>
            </p>
            <p class="list-group-item">
              Country: <%= recent_order.country %>
            </p>
            <p class="list-group-item">
              Quantity: <%= recent_order.quantity %>
            </p>
          </div>
          <hr />
        <% end %>
      <% else %>
        <div>
          <p>No orders yet.</p>
        </div>
      <% end %>
      </div>
    </div>
    <div class="col-md-3 recent-sold-container">
      <big>Reishi Teas Sold</big>
      <div class='recent-units-sold'>
        Today: <span class="badge"><%= @today_order_count %></span>
      </div>
      <hr />
      <div class='alltime-units-sold'>
        All Time: <span class="badge"><%= @alltime_order_count %></span>
      </div>
    </div>
    <div class="col-md-3 recent-shipped-container">
      <big>Reishi Teas Shipped</big>
      <div class="recent-units-shipped">
        Today: <span class="badge"><%= @today_shipped_count %></span>
      </div>
      <hr />
      <div class="alltime-units-shipped">
        All Time: <span class="badge"><%= @alltime_shipped_count %></span>
      </div>
    </div>
  </div>

</div>

<!-- separation -->
<div class="col-md-1">
</div>

<!-- sidebar -->
<div class="col-md-3">
  <%= render 'partials/sidebar' %>
</div>

app/views/orders/new.html.erb
<!-- main content -->
<div class="col-md-8">

  <div class="row">
    <div class="lead">
      <h1>Order some Reishi Tea</h1>
      <small>It is the Earth's Ultimate Beverage!</small>
    </div>
  </div>

  <div class="row">
    <%= render 'partials/order_form' %>
    <div class="voffset20"></div>
  </div>

</div>

<!-- separation -->
<div class="col-md-1">
</div>

<!-- sidebar -->
<div class="col-md-3">
  <%= render 'partials/sidebar' %>
</div>

app/views/partials/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="pull-left">&copy;&nbsp;
      <a href="https://github.com/stratigos" target="_blank">Todd Morningstar</a>, 2015
    </p>
    <p>&nbsp;&vert;&nbsp;This website is a
      <a href="/about">simple demonstration</a> and does not actually sell anything, ever.
    </p>
  </div>
</footer>

app/views/partials/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <nav>
      <div class="navbar-header">
        <%=
          link_to image_tag(
            'http://lorempixel.com/103/64/nature/',
            class: 'img-responsive',
            alt: 'Reishi Tea!',
            title: 'The World\'s Best Reishi Tea!'
          ), :root, id: 'logo'
        %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home',        :root %></li>
        <li><%= link_to 'About',       :about %></li>
        <li><%= link_to 'Reishi Info', :info %></li>
        <li><%= link_to 'Orders',      :orders_root %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/partials/_order_form.html.erb
<%= form_for @order, url: orders_create_path, method: :post do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <p><big>Please fix <%= pluralize(@order.errors.count, 'error') %> with your order:</big></p>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset id='new-order-fieldset'>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :street %>
      <%= f.text_field :street, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :postal %>
      <%= f.text_field :postal, class: 'form-control', maxlength: 10 %>
    </div>
    <div class="form-group">
      <%= f.label :country %>
      <%= f.text_field :country, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :quantity %>
      <%= f.text_field :quantity, class: 'form-control' %>
    </div>
  </fieldset>

  <fieldset id='new-order-comment-fieldset'>
    <%= f.fields_for :comment do |comment_f| %>
      <div class="form-group">
        <%= comment_f.label :body, 'Comment (optional)' %>
        <%= comment_f.text_area :body, class: 'form-control' %>
      </div>    
    <% end %>    
  </fieldset>

  <div class="voffset20"></div>

  <div class="form-group">
    <%= f.submit value: 'Place Order', class: 'btn btn-success shadow' %>
  </div>
<% end %>

app/views/partials/_shortorder_form.html.erb
<div class="shortorder-form-container">
  <p class="text-center"><em>If you would like to order, please enter your name, and amount of tea.</em></p>
  <form class="shortorder-form" action="/orders/new" method="get">
    <div class="form-group-sm">
      <input type="text" class="form-control" id="inputname" placeholder="Your Name">
    </div>
    <div class="voffset10"></div>
    <div class="form-group-sm">
      <input type="text" class="form-control" id="inputquantity" placeholder="Number of Teas">
    </div>
    <div class="voffset20"></div>
    <div class="text-center">
      <button type="submit" class="btn btn-success shadow">Click to Order</button>
    </div>
  </form>
</div>

app/views/partials/_sidebar.html.erb
<% # contained by div col-md-3 %>
<div class="reishitea-sidebar">
  <div class="well well-sm text-center">
    <p>Want to order? <strong><%= link_to 'Click here!', :orders_new %></strong></p>
    <p><small>HTTPS coming soon (we hope)!</small></p>
  </div>
  <div class="well well-sm text-center">
    <p>
      <img src="http://lorempixel.com/320/214/nature" class="img-responsive center-block" />
    </p>    
  </div>
  <div class="well well-sm text-center"> 
    <% if !@sidebar_comments.empty? %>
      <p>Top Customer Comments</p>
      <div class="list-group">
      <% @sidebar_comments.each_with_index do |comment, index| %>
        <% if index == 0 
          contclass = 'list-group-item active ligreen'
        else
          contclass = 'list-group-item'
        end %>
        <div class="<%= contclass %>">
          <h4 class="list-group-item-heading"><%= comment.order.name %>, <%= comment.order.country %></h4>
          <p class="list-group-item-text"><%= truncate comment.body, length: 60 %></p>
        </div>
      <% end %>
      </div>
    <% else %>
      <p>Enter a comment with this order form to see latest comments here!</p>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="col-md-8">
<!-- main content -->

  <div class="row">
    <div class="lead">
      <h1>About the Ultimate Beverage Site</h1>
      <small>This is just a demo application, it is not real <span class="glyphicon glyphicon-thumbs-up"></span></small>
    </div>
    <div class="clearfix"></div>
    <div>
      <hr />
      <p>
        This Rails 4 application uses the pub/sub service <a href="https://pusher.com/" target="_blank">Pusher</a>
        to facilitate real time updates on the <%= link_to 'orders page', orders_root_path %>. Also included is a rake
        task to assist with emulating orders and shipment activity (<code>./bin/rake buynship:emulate</code>). MySQL is
        the DBMS, jQuery moves stuff around in the DOM, and Twitter Bootstrap provides user facing goodness
        (can you tell?). You can view the application source, watch issues get fixed, and see features-in-progress 
        <a href="https://github.com/stratigos/reishitea" target="_blank">here</a>.
      </p>
      <hr/>
      <p>
        <a href="http://baconipsum.com/" target="_blank">Bacon ipsum</a> dolor amet enim brisket cow meatball short loin
         swine irure flank ut doner ball tip. Tongue commodo pancetta, aliqua capicola beef ribs boudin swine beef
         drumstick nisi. Minim t-bone tongue anim. Pork belly biltong prosciutto anim porchetta turkey et excepteur
         sirloin t-bone aliqua beef ribs. Laboris ut meatloaf pork chop sint tenderloin. Consequat frankfurter
         andouille pariatur kielbasa. Est sed officia, flank esse exercitation corned beef quis irure commodo tail
         andouille leberkas shankle kielbasa.
      </p>
      <p>
        Andouille labore in, nostrud enim filet mignon ullamco aliqua non reprehenderit fugiat spare ribs sausage
        pancetta. Occaecat incididunt sausage boudin. Biltong anim brisket pork chop. Adipisicing aliquip brisket
        officia, tenderloin prosciutto jowl drumstick irure. Sed leberkas picanha, nisi nulla ad in spare ribs.
        Venison tri-tip aliqua short ribs frankfurter qui pork belly nostrud strip steak ground round adipisicing
        dolore cow.
      </p>
      <p>
        Aute swine ut dolore culpa magna adipisicing short loin mollit. Cillum bacon ea eiusmod alcatra officia
        labore et deserunt sunt filet mignon elit. Prosciutto id leberkas, spare ribs shank ipsum aliquip. Pariatur
        laboris tail doner elit duis sint aliqua filet mignon bacon drumstick laborum lorem proident.
      </p>
    </div>

  </div>

</div>
<!-- separation -->
<div class="col-md-1">
</div>
<!-- sidebar -->
<div class="col-md-3">
  <%= render 'partials/sidebar' %>
</div>

app/views/welcome/index.html.erb
<div class="col-md-8">
<!-- main content -->
  <div class="row">
    <div class="well well-sm text-center">
      <div class="page-header">
        <h1>Reishi Tea!</h1>
        <h4>The most delicious beverage in the universe.</h4>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="row">
        <p class="text-center">
          <%= image_tag '/images/reishi_shot.jpg', class: 'img-responsive homepage-img', alt: 'Reishi Mushroom' %>
        </p>
        <p class="lead">Need a pick-me-up?</p>
        <p>
          Reishi tea is incredibly awesome and you should totally drink it. Its also kind of a pain to make, I mean
          boil for 90 minutes? <em>Aint nobody got time fo' dat!</em>. Luckily for you, I exist. When Im not 
          programming, Im probably making Reishi tea. Ive got a ton. I also have magic gnomes that can ship it to you
          in like ten seconds, so seriously place an order and you can get on the bountiful beverage bandwagon.
        </p>
        <p>
          Reishi can give you superpowers like spidey-man vision, anti-mutagenic cabability (seriously, YOU CAN FIGHT
          X-MEN!), and the ability to punch through solid concrete when youre 85 years old. These claims arent backed by
          anyone or anything ever, so you should try my tea and test for yourself. Besides, this isnt an ecommerce site,
          so I havent even implemented any way of taking money. Its free!
        </p>
      </div>
    </div>

    <div class="col-md-4">
      <div class="row">
        <ul id="homepage-fun-facts-list" class="list-group">
          <li class="list-group-item list-group-item-success">It puts the <em>fun</em> in <em>fungi!</em></li>
          <li class="list-group-item">Promotes a <strong>strong</strong> pretty much everything!</li>
          <li class="list-group-item list-group-item-success">Tastes like warm, savory wood!</li>
          <li class="list-group-item">Makes for a great gift!</li>
        </ul>
      </div>
      <div class="voffset20"></div>
      <div class="row">
        <%= render 'partials/shortorder_form' %>
      </div>
    </div>
  </div>

</div>
<!-- separation -->
<div class="col-md-1">
</div>
<!-- sidebar -->
<div class="col-md-3">
  <%= render 'partials/sidebar' %>
</div>

app/views/welcome/info.html.erb
<div class="col-md-8">
<!-- main content -->

  <div class="row">
    <p class="pull-left">
      <%= image_tag '/images/reishi_shot.jpg',
        width: '50%', height: '50%', class: 'img-responsive', alt: 'Reishi Mushroom'
      %>
    </p>
    <div>
      <h1><strong>Reishi is <em>totally</em> cool.</strong></h1>
      <p class="text-center voffset20">
        <a href="https://duckduckgo.com/?q=reishi+tea" target="_blank" class="btn btn-success">Learn More!</a>
      </p>
    </div>
    <div class="clearfix"></div>
    <div>
      <hr />
      <p>
        Red Reishi (Ganoderma lucidum), commonly known as Ling Zhi in Chinese, is a herbal mushroom known to have miraculous health benefits.
      </p>
      <p>
        - <a href="http://www.reishi.com/" target="_blank">reishi.com</a>
      </p>
      <hr />
      <p>
        Reishi mushroom is a fungus that some people describe as “tough” and “woody” with a bitter taste. The fruiting
        body (above-ground part) and mycelium (filaments connecting a group of mushrooms) are used as medicine.
      </p>
      <p>
        Reishi mushroom is used for boosting the immune system; viral infections such as the flu (influenza), swine flu,
        and avian flu; lung conditions including asthma and bronchitis; heart disease and contributing conditions such
        as high blood pressure and high cholesterol; kidney disease; cancer; and liver disease. It is also used for
        HIV/AIDS, altitude sickness, chronic fatigue syndrome (CFS), trouble sleeping (insomnia), stomach ulcers,
        poisoning, and herpes pain. Other uses include reducing stress and preventing fatigue.
      </p>
      <p>
        In combination with other herbs, reishi mushroom is used to treat prostate cancer.
      </p>
      <p>
        - <a
          href="http://www.webmd.com/vitamins-supplements/ingredientmono-905-reishi%20mushroom.aspx?activeingredientid=905&activeingredientname=reishi%20mushroom"
          target="_blank"
        >WebMD</a>
      </p>
      <hr/>
      <p>
       The benefits of reishi mushrooms are so well known and proven that you can get them in forms that are much
       convenient that slicing them up and cooking with them. You can buy them dried, in concentrated tablets, capsules,
       or even as an extract. In any of these forms reishi mushrooms can be used as a dietary supplement.
      </p>
      <p>
        - <a href="http://www.herbwisdom.com/herb-reishi-mushrooms.html" target="_blank">HerbWisdom</a>
      </p>
      <hr />
      <p>
        For over 2,000 years, reishi mushrooms have kept people spry and healthy well into their golden years. Or at
        least, that’s what people have been saying. According to some herbalists, red reishi mushrooms can cure many of
        the issues we associate with aging, such as high blood pressure, arthritis, and liver problems.
      </p>
      <p>
        - <a href="http://www.healthline.com/health/reishi-mushroom-key-to-immortality" target="_blank">HealthLine</a>
      </p>
      <hr />
      <p class="text-center">
        <a href="https://duckduckgo.com/?q=reishi+tea" target="_blank" class="btn btn-success">Learn More!</a>
      </p>
      <hr />
    </div>
    <div class="voffset20"></div>
  </div>

</div>
<!-- separation -->
<div class="col-md-1">
</div>
<!-- sidebar -->
<div class="col-md-3">
  <%= render 'partials/sidebar' %>
</div>